plugins {
    id "net.fabricmc.fabric-loom-remap"
}

base {
    archivesName = "chunksfadein-fabric"
}

loom {
    mixin {
        defaultRefmapName.set("chunksfadein.refmap.json")
    }
}

sourceSets.main.java {
    srcDir project(":common").sourceSets.main.java
}
sourceSets.main.resources {
    srcDir project(":common").sourceSets.main.resources
}

sourceSets {
    sodium_v6 {
        java.srcDir project(":common").file("src/sodium_v6/java")
        compileClasspath += sourceSets.main.output +
                sourceSets.main.compileClasspath.filter { !it.name.toLowerCase().contains("sodium") }
    }
}

loom {
    addRemapConfiguration("sodium_v6_modCompileOnly") {
        sourceSet = sourceSets.sodium_v6
        targetConfigurationName = "sodium_v6_modCompileOnly"
        onCompileClasspath = true
        onRuntimeClasspath = false
    }
}

jar {
    from sourceSets.sodium_v6.output
}

dependencies {
    sodium_v6_modCompileOnly "maven.modrinth:sodium:${sodium_old_version}"

    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    include "com.moandjiezana.toml:toml4j:${toml4j_version}"
    include "net.fabricmc.fabric-api:fabric-key-binding-api-v1:${fabric_key_binding_api_version}"

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-key-binding-api-v1:${fabric_key_binding_api_version}"

    modImplementation "maven.modrinth:sodium:${sodium_version}-fabric"
    modImplementation "maven.modrinth:iris:${iris_version}-fabric"
    modImplementation "maven.modrinth:distanthorizons:${dh_version}"
    modImplementation "com.terraformersmc:modmenu:${modmenu_version}"

    implementation "com.moandjiezana.toml:toml4j:${toml4j_version}"
    implementation "io.github.douira:glsl-transformer:${glsl_transformer_version}"
    implementation "org.anarres:jcpp:1.4.14"

    implementation project(":common")
}
