# Project
version = 3.0.20-26.1
group = com.koteinik.chunksfadein
java_version = 25

# Minecraft
minecraft_version = 26.1
minecraft_version_range_fabric = >=26.1
minecraft_version_range_neoforge = [26.1, 26.1.1, 26.1.2]

# Parchment
parchment_minecraft = 1.21
parchment_version = 2024.07.28

# Fabric
fabric_version = 0.144.0+26.1
fabric_loader_version = 0.18.4
fabric_key_binding_api_version = 1.1.8+9c919dacc9

# NeoForge
neoforge_version = 26.1.0.1-beta

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

# Dependencies
sodium_version = mc26.1.2-0.8.12-beta.4-fabric
sodium_version_range_fabric = >=0.8.7
sodium_version_range_neoforge = [0.8.7,)

iris_version = 1.10.9+26.1-fabric
iris_version_range_fabric = <1.10.7
iris_version_range_neoforge = [1.10.7,)

dh_version = 3.0.1-b-26.1.2
modmenu_version = 18.0.0-alpha.7
crowdin_translate_version = 1.0.0
toml4j_version = 0.7.2
glsl_transformer_version = 2.0.1
mixin_constraints_version = 1.0.1
