plugins {
    id "net.neoforged.moddev"
    id "com.gradleup.shadow" version "9.0.0"
}

base {
    archivesName = "chunksfadein-neoforge"
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

sourceSets.main.java {
    srcDir project(":common").sourceSets.main.java
}
sourceSets.main.resources {
    srcDir project(":common").sourceSets.main.resources
}

sourceSets {
    sodium_v6 {
        java.srcDir project(":common").file("src/sodium_v6/java")
        compileClasspath += sourceSets.main.output +
                sourceSets.main.compileClasspath.filter { !it.name.toLowerCase().contains("sodium") }
    }
}

configurations {
    shade
    implementation.extendsFrom shade
}

dependencies {
    implementation project(":common")

    sodium_v6CompileOnly "maven.modrinth:sodium:${sodium_old_version.replace("fabric", "neoforge")}"

    implementation "maven.modrinth:sodium:${sodium_version.replace("fabric", "neoforge")}"
    implementation "maven.modrinth:iris:${iris_version.replace("fabric", "neoforge")}"
    implementation "maven.modrinth:distanthorizons:${dh_version}"
    implementation "maven.modrinth:embeddium:${embeddium_version}"
    implementation "maven.modrinth:sable:${sable_version}"

    jarJar api("dev.ryanhcode.sable-companion:sable-companion-common-1.21.1:${sable_companion_version}")

    compileOnly project(":common").sourceSets.main.compileClasspath.filter { file ->
        def fileName = file.name.toLowerCase()
        return (fileName.contains("sodium") || fileName.contains("iris")) && !fileName.contains("minecraft")
    }

    implementation "org.anarres:jcpp:1.4.14"
    implementation "io.github.douira:glsl-transformer:${glsl_transformer_version}"

    shade("com.moandjiezana.toml:toml4j:${toml4j_version}") {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
}

shadowJar {
    configurations = [project.configurations.shade]

    from sourceSets.sodium_v6.output

    relocate 'com.moandjiezana.toml', 'chunksfadein.repack.com.moandjiezana.toml'

    archiveClassifier = ''
}

tasks.named('assemble') {
    dependsOn tasks.shadowJar
}

tasks.named('jar', Jar) {
    manifest {
        attributes([
                "Implementation-Title"  : project.name,
                "Implementation-Version": project.version
        ])
    }
}
