name: Publish release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Build
        run: ./gradlew clean build

      - name: Publish Fabric/Quilt
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 720811
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: JaNmzvA8
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"
          modrinth-featured: false

          github-token: "${{secrets.GITHUB_TOKEN}}"

          name: "${{github.event.release.name}} for Fabric"
          version: "${{github.ref_name}}-fabric"

          loaders: |
            fabric
            quilt

          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
            fabric/build/libs/*-@(dev|sources|javadocs).jar

          dependencies: |
            sodium(required){modrinth:AANobbMI}{curseforge:394468}
            iris(optional){modrinth:YL57xq9U}{curseforge:455508}
            optifabric(incompatible){curseforge:322385}#(ignore:modrinth)

          java: |
            17
            18
            21

          game-version-filter: releases

      - name: Publish NeoForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 720811
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: JaNmzvA8
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"
          modrinth-featured: false

          github-token: "${{secrets.GITHUB_TOKEN}}"

          name: "${{github.event.release.name}} for NeoForge"
          version: "${{github.ref_name}}-neoforge"

          loaders: |
            neoforge

          game-versions: |
            [1.21, 1.21.1]

          files: |
            neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar
            neoforge/build/libs/*-@(dev|sources|javadocs).jar

          dependencies: |
            sodium(required){modrinth:AANobbMI}{curseforge:394468}
            iris(optional){modrinth:YL57xq9U}{curseforge:455508}
            optifabric(incompatible){curseforge:322385}#(ignore:modrinth)

          java: |
            17
            18
            21

          game-version-filter: releases
